language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.1

before_install:
  - composer self-update
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - mv box.phar box
  - chmod 755 box

install:
  - composer install --prefer-source --no-interaction
  - ls -lat vendor

script:
  - ./vendor/bin/phpunit
  - rm -rf vendor
  - composer install --no-dev
  - ls -lat vendor
  - ~/.phpenv/versions/5.6/bin/php box build
  - ls -lat
